## Semi-supervised approach for Named-Entity Recognition

### Imports

In [101]:
import pandas as pd
import os
import nltk
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import f1_score, classification_report
from bs4 import BeautifulSoup
from nltk.corpus import names,gazetteers 
from sklearn_crfsuite import CRF
from sklearn_crfsuite.metrics import flat_f1_score, flat_classification_report
import re

### Importing the tagged training data consisting of GTP generated sentences and amazon reviews

In [102]:
data= pd.read_csv('Heyday_trainingdata.csv')

In [103]:
data

      Sentence_Index   Tokens         Tags
0                  0  "Hello,            O
1                  0        I            O
2                  0     need            O
3                  0        a            O
4                  0  standup  I-ATTRIBUTE
...              ...      ...          ...
3731             337  inches)            O
3732             337       of            O
3733             337     even            O
3734             337   tinier  I-ATTRIBUTE
3735             337  magnets  I-ATTRIBUTE

[3736 rows x 3 columns]

### Data Wrangling

In [104]:
data['Sentence']= data[['Sentence_Index','Tokens','Tags']].groupby(['Sentence_Index'])['Tokens'].transform(lambda x: ' '.join(x))

In [105]:
data['Tags']= data[['Sentence_Index','Tokens','Tags']].groupby(['Sentence_Index'])['Tags'].transform(lambda x: ','.join(x))

In [106]:
data = data[['Sentence','Tags']]

In [107]:
data = data.drop_duplicates().reset_index(drop=True)

In [108]:
data

,Sentence,Tags
0,"""Hello, I need a standup shower door only, no ...","O,O,O,O,I-ATTRIBUTE,I-PRODUCT,I-PRODUCT,O,O,I-..."
1,I'm looking for a double sink kitchen close to...,"O,O,O,O,I-ATTRIBUTE,I-PRODUCT,I-PRODUCT,O,O,I-..."
2,"""I'm looking for bypass shower doors in chrome...","O,O,O,O,I-PRODUCT,I-PRODUCT,O,I-MATERIAL,O,I-M..."
3,"""I am looking at the 34""""x34"""" shower kit with...","O,O,O,O,O,I-SIZE,I-PRODUCT,I-PRODUCT,O,I-ATTRI..."
4,"""Can the 2"""" backsplash, on the 60"""" single si...","O,O,I-SIZE,I-ATTRIBUTE,O,O,I-SIZE,I-PRODUCT,I-..."
...,...,...
261,Great for kids learning to read,"O,O,O,O,O,O"
262,They weren't kidding about this being a little...,"O,O,O,O,O,O,O,O,O"
263,"Students in my office exact comment: ""These ar...","O,O,O,O,I-PRODUCT,I-PRODUCT,O,O,O"
264,love it,"O,O"
265,The price is waaaaay too high for this tiny ti...,"O,O,O,O,O,O,O,O,O,O,O,O,I-SIZE,I-SIZE,O,I-SIZE..."

### Loading the training and validation set

In [109]:
train_dataset= data
test_dataset = pd.read_csv('un-negated_clean_data.csv')
test_dataset = test_dataset[["Tokens","Tags","sentence"]]
test_dataset = test_dataset.replace('B-','I-', regex=True)
test_dataset['Sentence']= test_dataset[['sentence','Tokens','Tags']].groupby(['sentence'])['Tokens'].transform(lambda x: ' '.join(x))
test_dataset['Tags']= test_dataset[['sentence','Tokens','Tags']].groupby(['sentence'])['Tags'].transform(lambda x: ','.join(x))
test_dataset = test_dataset[['Sentence','Tags']]
test_dataset = test_dataset.drop_duplicates().reset_index(drop=True)

In [110]:
test_dataset

,Sentence,Tags
0,I am looking for a black gloss 33 inch firecla...,"O,O,O,O,O,I-COLOUR,I-TEXTURE,I-SIZE,I-SIZE,I-P..."
1,Looking for pre workout Pump addict instead of...,"O,O,I-PRODUCT,I-PRODUCT,I-PRODUCT,I-PRODUCT,O,..."
2,i need a 48 inch glass sliding goof and a show...,"O,O,O,I-SIZE,I-SIZE,I-MATERIAL,I-PRODUCT,I-PRO..."
3,"Hello, do any of your free standing tubs have ...","O,O,O,O,O,I-ATTRIBUTE,I-ATTRIBUTE,I-PRODUCT,O,..."
4,I'm looking for a 24 inch white mirror that is...,"O,O,O,O,I-SIZE,I-SIZE,I-COLOUR,I-PRODUCT,O,O,I..."
...,...,...
162,What rectangular shower units are available?,"O,I-SHAPE,I-PRODUCT,I-PRODUCT,O,O"
163,I am looking for a 35 inch bathroom sink count...,"O,O,O,O,O,I-SIZE,I-SIZE,I-PRODUCT,I-PRODUCT,I-..."
164,I'm looking f or a Black Matte bathtub double ...,"O,O,O,O,O,I-COLOUR,I-TEXTURE,I-PRODUCT,I-PRODU..."
165,Need a 27 inch frameless shower door,"O,O,I-SIZE,I-SIZE,I-ATTRIBUTE,I-PRODUCT,I-PRODUCT"
166,Looking for 30 inch white desk set,"O,O,I-SIZE,I-SIZE,I-COLOUR,I-PRODUCT,I-PRODUCT"

In [111]:
def strsplit_tags(tags):
    sent_list = tags.split(",")
    return sent_list

In [112]:
def strsplit_sentence(sentence):
    sent_list = sentence.split(" ")
    return sent_list

In [113]:
train_sents = []

for index, row in train_dataset.iterrows():
    train_sents.append((strsplit_sentence(row['Sentence']),strsplit_tags(row['Tags'])))

In [114]:
dev_sents = []

for index, row in test_dataset.iterrows():
    dev_sents.append((strsplit_sentence(row['Sentence']),strsplit_tags(row['Tags'])))

### Creating features using knowledge bases

In [115]:
colors = pd.read_csv("colors.csv")

In [116]:
colors

       air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
0     air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
1    air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
2         alabama_crimson        Alabama Crimson  #a32638  163   38   56
3              alice_blue             Alice Blue  #f0f8ff  240  248  255
4        alizarin_crimson       Alizarin Crimson  #e32636  227   38   54
..                    ...                    ...      ...  ...  ...  ...
859         yellow_orange          Yellow Orange  #ffae42  255  174   66
860        yellow_process       Yellow (Process)  #ffef00  255  239    0
861            yellow_ryb           Yellow (Ryb)  #fefe33  254  254   51
862                zaffre                 Zaffre  #0014a8    0   20  168
863     zinnwaldite_brown      Zinnwaldite Brown  #2c1608   44   22    8

[864 rows x 6 columns]

In [117]:
color_list= []
for index, row in colors.iterrows():
    color_list.append(row['Air Force Blue (Raf)'])

In [118]:
products = pd.read_csv('products.csv',sep='\t')

In [119]:
product_list =[]
for index, row  in products.iterrows():
    for i in row[0].split():
        if i[-1]=='s':
            product_list.append(i[:-1])
        else:
            product_list.append(i)

In [120]:
product_list = set(product_list)
product_list = list(product_list)

### Feature Engineering

In [121]:

import nltk


def get_pos(word):
    tag = nltk.pos_tag([word])
    return tag[0][1]

def is_number(string):
    return any(char.isdigit() for char in string)

def word2features(sentence, idx):
    word_features = {}
    word_features['word_lowercase'] = sentence[idx].lower()

    ## Features looking at the neighbouring words:
    
    if idx > 0:
        word_features["pre_word"] = sentence[idx -1].lower()
    else:
        word_features["pre_word"] = ""
    if idx < len(sentence) - 1:
        word_features["next_word"] = sentence[idx +1].lower()
    else:
        word_features["next_word"] = ""
        
    if idx > 1:
        word_features["pre2_word"] = sentence[idx -2].lower()
    else:
        word_features["pre2_word"] = ""
        
    if idx < len(sentence) - 2:
        word_features["next2_word"] = sentence[idx +2].lower()
    else:
        word_features["next2_word"] = ""
    ## Features loking at the word endings
    
    if len(sentence[idx])> 2:
        word_features["last2char"] = sentence[idx][-2:]
    else:
        word_features["last2char"] = sentence[idx]
    
    if len(sentence[idx])> 3:
        word_features["last3char"] = sentence[idx][-3:]
    else:
        word_features["last3char"] = sentence[idx]
        
    ## Features considering the shape of the word
    
    if sentence[idx].isupper():
        word_features["upper"] = True
    else:
        word_features["upper"] = False  
        
    if sentence[idx].islower():
        word_features["lower"] = True
    else:
        word_features["lower"] = False 
    
    word_features["length"] = len(sentence[idx])
    word_features["position"] = idx
    
    
    ## Extra Features:
    
    ## Is Number
    word_features["number"] = is_number(sentence[idx])
    
#     if is_number(sentence[idx]) == True:
#         word_features["num_length"] = len(sentence[idx])
#     else:
#         word_features["num_length"] = 0
    
    ##Is_Noun
    
    if get_pos(sentence[idx])== "NN":
        word_features["is_noun"] = True
    else:
        word_features["is_noun"] = False
    

#     color Feature:
    
    if sentence[idx].lower() in color_list:
        word_features["color"] = True
    else:
        word_features["color"] = False
        
#     Product Feature:
    
    if sentence[idx].lower() in product_list:
        word_features["product"] = True
    else:
        word_features["product"] = False



        
    for i in range(len(sentence)):
        if i == idx and i != 0:
            word_features['first_word_not_in_title_case'] = sentence[idx].istitle()
        elif i == idx and i == 0:
            if sentence[idx].istitle():
                word_features['first_word_not_in_title_case'] = False
    
        
    return word_features
    
    
def sentence2features(sentence):
    return [word2features(sentence, idx) for idx in range(len(sentence))]

In [122]:
def prepare_ner_feature_dicts(sents):
    '''ner_files is a list of Ontonotes files with NER annotations. Returns feature dictionaries and 
    IOB tags for each token in the entire dataset'''
    all_dicts = []
    all_tags = []
    # your code here
    for tokens, tags in sents:
        all_dicts.append(sentence2features(tokens))
        all_tags.append(tags)

    return all_dicts, all_tags

In [123]:
train_dicts, train_tags = prepare_ner_feature_dicts(train_sents)
dev_dicts, dev_tags = prepare_ner_feature_dicts(dev_sents)

### CRF Model

In [124]:
import sklearn_crfsuite

crf = sklearn_crfsuite.CRF(
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=350,
    all_possible_transitions=True,
    verbose = True
)
crf.fit(train_dicts, train_tags)
try:
    call_produces_an_error()
except:
    pass

loading training data to CRFsuite: 100%|██████████| 266/266 [00:00<00:00, 3405.15it/s]

Feature generation
type: CRF1d
feature.minfreq: 0.000000
feature.possible_states: 0
feature.possible_transitions: 1
0....1....2....3....4....5....6....7....8....9....10
Number of features: 7199
Seconds required: 0.021

L-BFGS optimization
c1: 0.100000
c2: 0.100000
num_memories: 6
max_iterations: 350
epsilon: 0.000010
stop: 10
delta: 0.000010
linesearch: MoreThuente
linesearch.max_iterations: 20

Iter 1   time=0.01  loss=4575.83  active=7172  feature_norm=0.50
Iter 2   time=0.00  loss=4094.20  active=6892  feature_norm=0.42
Iter 3   time=0.00  loss=3570.06  active=6871  feature_norm=0.37
Iter 4   time=0.00  loss=3436.77  active=7034  feature_norm=0.43
Iter 5   time=0.00  loss=3197.22  active=7078  feature_norm=0.58
Iter 6   time=0.00  loss=3048.60  active=6932  feature_norm=0.91
Iter 7   time=0.00  loss=2854.62  active=7049  feature_norm=0.94
Iter 8   time=0.00  loss=2744.74  active=7033  feature_norm=1.07
Iter 9   time=0.00  loss=2356.51  active=7009  feature_norm=1.88
Iter 10  time=0.00  loss=2312.30  active=7093  feature_norm=2.59
Iter 11  time=0.00  loss=2057.23  active=7127  feature_norm=2.66
Iter 12  time=0.00  loss=2002.48  active=7166  feature_norm=2.92
Iter 13  time=0.00  loss=1948.21  active=7170  feature_norm=3.27
Iter 14  time=0.00  loss=1914.82  active=7171  feature_norm=3.40
Iter 15  time=0.00  loss=1849.11  active=7171  feature_norm=3.60
Iter 16  time=0.00  loss=1805.68  active=7167  feature_norm=3.72
Iter 17  time=0.00  loss=1670.78  active=7124  feature_norm=4.26
Iter 18  time=0.00  loss=1577.11  active=6772  feature_norm=5.31
Iter 19  time=0.00  loss=1489.74  active=6868  feature_norm=5.38
Iter 20  time=0.00  loss=1471.90  active=6900  feature_norm=5.45
Iter 21  time=0.00  loss=1438.47  active=6901  feature_norm=5.62
Iter 22  time=0.00  loss=1377.86  active=6847  feature_norm=6.17
Iter 23  time=0.00  loss=1307.21  active=6747  feature_norm=7.76
Iter 24  time=0.00  loss=1171.54  active=6729  feature_norm=8.90
Iter 25  time=0.00  loss=1083.29  active=6640  feature_norm=10.42
Iter 26  time=0.00  loss=939.03   active=6280  feature_norm=13.94
Iter 27  time=0.00  loss=898.13   active=6233  feature_norm=15.63
Iter 28  time=0.00  loss=831.19   active=6212  feature_norm=16.82
Iter 29  time=0.00  loss=781.97   active=6118  feature_norm=18.21
Iter 30  time=0.00  loss=702.91   active=6037  feature_norm=20.83
Iter 31  time=0.00  loss=653.12   active=5988  feature_norm=23.68
Iter 32  time=0.00  loss=595.15   active=6012  feature_norm=25.04
Iter 33  time=0.00  loss=568.32   active=5990  feature_norm=25.95
Iter 34  time=0.00  loss=505.06   active=5771  feature_norm=28.66
Iter 35  time=0.00  loss=486.36   active=5734  feature_norm=29.62
Iter 36  time=0.00  loss=464.92   active=5717  feature_norm=29.97
Iter 37  time=0.00  loss=445.74   active=5689  feature_norm=30.33
Iter 38  time=0.00  loss=425.68   active=5653  feature_norm=31.21
Iter 39  time=0.00  loss=415.76   active=5619  feature_norm=31.55
Iter 40  time=0.00  loss=407.43   active=5583  feature_norm=31.81
Iter 41  time=0.00  loss=399.42   active=5301  feature_norm=32.04
Iter 42  time=0.00  loss=393.86   active=5137  feature_norm=32.21
Iter 43  time=0.00  loss=390.21   active=4817  feature_norm=32.26
Iter 44  time=0.00  loss=387.53   active=4704  feature_norm=32.37
Iter 45  time=0.00  loss=383.85   active=4371  feature_norm=32.52
Iter 46  time=0.00  loss=381.16   active=4305  feature_norm=32.57
Iter 47  time=0.00  loss=378.86   active=4017  feature_norm=32.72
Iter 48  time=0.00  loss=376.01   active=3931  feature_norm=32.83
Iter 49  time=0.00  loss=374.75   active=3941  feature_norm=32.85
Iter 50  time=0.00  loss=372.92   active=3892  feature_norm=32.87
Iter 51  time=0.00  loss=371.20   active=3776  feature_norm=32.89
Iter 52  time=0.00  loss=369.43   active=3746  feature_norm=32.83
Iter 53  time=0.00  loss=368.18   active=3717  feature_norm=32.83
Iter 54  time=0.00  loss=366.57   active=3632  feature_norm=32.78
Iter 55  time=0.00  loss=364.94   active=3545  feature_norm=32.79
Iter 56  time=0.00  loss=363.75   active=3467  feature_norm=32.78
Iter 57  time=0.00  loss=362.66   active=3458  feature_norm=32.84
Iter 58  time=0.00  loss=362.07   active=3440  feature_norm=32.82
Iter 59  time=0.00  loss=361.35   active=3432  feature_norm=32.84
Iter 60  time=0.00  loss=360.59   active=3400  feature_norm=32.82
Iter 61  time=0.00  loss=359.92   active=3362  feature_norm=32.86
Iter 62  time=0.00  loss=359.22   active=3370  feature_norm=32.85
Iter 63  time=0.00  loss=358.64   active=3366  feature_norm=32.87
Iter 64  time=0.00  loss=358.30   active=3360  feature_norm=32.85
Iter 65  time=0.00  loss=357.85   active=3336  feature_norm=32.87
Iter 66  time=0.00  loss=357.49   active=3325  feature_norm=32.84
Iter 67  time=0.00  loss=357.02   active=3320  feature_norm=32.84
Iter 68  time=0.00  loss=356.69   active=3308  feature_norm=32.82
Iter 69  time=0.00  loss=356.25   active=3297  feature_norm=32.83
Iter 70  time=0.00  loss=355.93   active=3271  feature_norm=32.82
Iter 71  time=0.00  loss=355.60   active=3248  feature_norm=32.82
Iter 72  time=0.00  loss=355.30   active=3239  feature_norm=32.81
Iter 73  time=0.00  loss=355.01   active=3220  feature_norm=32.81
Iter 74  time=0.00  loss=354.71   active=3209  feature_norm=32.79
Iter 75  time=0.00  loss=354.46   active=3187  feature_norm=32.78
Iter 76  time=0.00  loss=354.06   active=3192  feature_norm=32.76
Iter 77  time=0.00  loss=353.84   active=3186  feature_norm=32.76
Iter 78  time=0.00  loss=353.55   active=3187  feature_norm=32.74
Iter 79  time=0.00  loss=353.31   active=3168  feature_norm=32.73
Iter 80  time=0.00  loss=352.95   active=3156  feature_norm=32.71
Iter 81  time=0.00  loss=352.68   active=3145  feature_norm=32.71
Iter 82  time=0.00  loss=352.38   active=3142  feature_norm=32.68
Iter 83  time=0.00  loss=352.14   active=3144  feature_norm=32.68
Iter 84  time=0.00  loss=351.86   active=3124  feature_norm=32.65
Iter 85  time=0.00  loss=351.61   active=3119  feature_norm=32.65
Iter 86  time=0.00  loss=351.32   active=3111  feature_norm=32.62
Iter 87  time=0.00  loss=351.08   active=3098  feature_norm=32.62
Iter 88  time=0.00  loss=350.82   active=3075  feature_norm=32.60
Iter 89  time=0.00  loss=350.59   active=3061  feature_norm=32.60
Iter 90  time=0.00  loss=350.39   active=3055  feature_norm=32.59
Iter 91  time=0.00  loss=350.24   active=3054  feature_norm=32.60
Iter 92  time=0.00  loss=350.05   active=3044  feature_norm=32.58
Iter 93  time=0.00  loss=349.87   active=3046  feature_norm=32.58
Iter 94  time=0.00  loss=349.61   active=3027  feature_norm=32.56
Iter 95  time=0.00  loss=349.50   active=3032  feature_norm=32.56
Iter 96  time=0.00  loss=349.31   active=3030  feature_norm=32.55
Iter 97  time=0.00  loss=349.20   active=3018  feature_norm=32.54
Iter 98  time=0.00  loss=349.05   active=3004  feature_norm=32.52
Iter 99  time=0.00  loss=348.94   active=3000  feature_norm=32.51
Iter 100 time=0.00  loss=348.79   active=2996  feature_norm=32.49
Iter 101 time=0.00  loss=348.68   active=2997  feature_norm=32.49
Iter 102 time=0.00  loss=348.58   active=2988  feature_norm=32.47
Iter 103 time=0.00  loss=348.50   active=2987  feature_norm=32.48
Iter 104 time=0.00  loss=348.41   active=2975  feature_norm=32.46
Iter 105 time=0.00  loss=348.33   active=2968  feature_norm=32.46
Iter 106 time=0.00  loss=348.24   active=2972  feature_norm=32.45
Iter 107 time=0.00  loss=348.18   active=2966  feature_norm=32.46
Iter 108 time=0.00  loss=348.11   active=2972  feature_norm=32.44
Iter 109 time=0.00  loss=348.06   active=2970  feature_norm=32.45
Iter 110 time=0.00  loss=348.00   active=2971  feature_norm=32.44
Iter 111 time=0.00  loss=347.92   active=2973  feature_norm=32.45
Iter 112 time=0.00  loss=347.86   active=2968  feature_norm=32.44
Iter 113 time=0.00  loss=347.80   active=2967  feature_norm=32.44
Iter 114 time=0.00  loss=347.77   active=2957  feature_norm=32.44
Iter 115 time=0.00  loss=347.67   active=2961  feature_norm=32.44
Iter 116 time=0.00  loss=347.63   active=2964  feature_norm=32.43
Iter 117 time=0.00  loss=347.56   active=2962  feature_norm=32.43
Iter 118 time=0.00  loss=347.52   active=2959  feature_norm=32.43
Iter 119 time=0.00  loss=347.45   active=2957  feature_norm=32.43
Iter 120 time=0.00  loss=347.44   active=2952  feature_norm=32.43
Iter 121 time=0.00  loss=347.36   active=2952  feature_norm=32.43
Iter 122 time=0.00  loss=347.35   active=2955  feature_norm=32.43
Iter 123 time=0.00  loss=347.29   active=2958  feature_norm=32.43
Iter 124 time=0.00  loss=347.26   active=2960  feature_norm=32.43
Iter 125 time=0.00  loss=347.22   active=2964  feature_norm=32.43
Iter 126 time=0.00  loss=347.21   active=2965  feature_norm=32.44
Iter 127 time=0.00  loss=347.15   active=2968  feature_norm=32.44
Iter 128 time=0.00  loss=347.15   active=2969  feature_norm=32.44
Iter 129 time=0.00  loss=347.09   active=2963  feature_norm=32.45
Iter 130 time=0.00  loss=347.08   active=2960  feature_norm=32.45
Iter 131 time=0.00  loss=347.03   active=2957  feature_norm=32.46
Iter 132 time=0.00  loss=347.03   active=2951  feature_norm=32.46
Iter 133 time=0.00  loss=346.98   active=2953  feature_norm=32.47
Iter 134 time=0.00  loss=346.98   active=2949  feature_norm=32.47
Iter 135 time=0.00  loss=346.93   active=2950  feature_norm=32.48
Iter 136 time=0.00  loss=346.92   active=2945  feature_norm=32.48
Iter 137 time=0.00  loss=346.88   active=2943  feature_norm=32.49
Iter 138 time=0.00  loss=346.87   active=2938  feature_norm=32.50
Iter 139 time=0.00  loss=346.83   active=2940  feature_norm=32.50
Iter 140 time=0.00  loss=346.82   active=2942  feature_norm=32.51
Iter 141 time=0.00  loss=346.79   active=2941  feature_norm=32.52
Iter 142 time=0.00  loss=346.77   active=2939  feature_norm=32.53
Iter 143 time=0.00  loss=346.74   active=2935  feature_norm=32.53
Iter 144 time=0.00  loss=346.72   active=2936  feature_norm=32.54
Iter 145 time=0.00  loss=346.69   active=2934  feature_norm=32.54
Iter 146 time=0.00  loss=346.67   active=2928  feature_norm=32.55
Iter 147 time=0.00  loss=346.63   active=2929  feature_norm=32.55
Iter 148 time=0.00  loss=346.61   active=2927  feature_norm=32.56
Iter 149 time=0.00  loss=346.57   active=2921  feature_norm=32.56
Iter 150 time=0.00  loss=346.55   active=2920  feature_norm=32.57
Iter 151 time=0.00  loss=346.51   active=2918  feature_norm=32.57
Iter 152 time=0.00  loss=346.49   active=2915  feature_norm=32.57
Iter 153 time=0.00  loss=346.46   active=2912  feature_norm=32.58
Iter 154 time=0.00  loss=346.43   active=2909  feature_norm=32.58
Iter 155 time=0.00  loss=346.41   active=2913  feature_norm=32.58
Iter 156 time=0.00  loss=346.38   active=2907  feature_norm=32.59
Iter 157 time=0.00  loss=346.35   active=2908  feature_norm=32.59
Iter 158 time=0.00  loss=346.32   active=2909  feature_norm=32.60
Iter 159 time=0.00  loss=346.29   active=2909  feature_norm=32.61
Iter 160 time=0.00  loss=346.26   active=2909  feature_norm=32.61
Iter 161 time=0.00  loss=346.24   active=2910  feature_norm=32.63
Iter 162 time=0.00  loss=346.20   active=2903  feature_norm=32.63
Iter 163 time=0.00  loss=346.18   active=2900  feature_norm=32.64
Iter 164 time=0.00  loss=346.15   active=2899  feature_norm=32.64
Iter 165 time=0.00  loss=346.13   active=2897  feature_norm=32.65
Iter 166 time=0.00  loss=346.10   active=2898  feature_norm=32.65
Iter 167 time=0.00  loss=346.07   active=2896  feature_norm=32.66
Iter 168 time=0.00  loss=346.04   active=2887  feature_norm=32.66
Iter 169 time=0.00  loss=346.01   active=2886  feature_norm=32.66
Iter 170 time=0.00  loss=345.98   active=2885  feature_norm=32.66
Iter 171 time=0.00  loss=345.95   active=2888  feature_norm=32.67
Iter 172 time=0.00  loss=345.91   active=2884  feature_norm=32.66
Iter 173 time=0.00  loss=345.89   active=2885  feature_norm=32.66
Iter 174 time=0.00  loss=345.86   active=2878  feature_norm=32.67
Iter 175 time=0.00  loss=345.84   active=2876  feature_norm=32.67
Iter 176 time=0.00  loss=345.81   active=2873  feature_norm=32.67
Iter 177 time=0.00  loss=345.78   active=2873  feature_norm=32.67
Iter 178 time=0.00  loss=345.75   active=2872  feature_norm=32.67
Iter 179 time=0.00  loss=345.72   active=2866  feature_norm=32.67
Iter 180 time=0.00  loss=345.71   active=2855  feature_norm=32.66
Iter 181 time=0.00  loss=345.68   active=2852  feature_norm=32.66
Iter 182 time=0.00  loss=345.66   active=2846  feature_norm=32.65
Iter 183 time=0.00  loss=345.64   active=2837  feature_norm=32.64
Iter 184 time=0.00  loss=345.61   active=2842  feature_norm=32.64
Iter 185 time=0.00  loss=345.60   active=2841  feature_norm=32.63
Iter 186 time=0.00  loss=345.58   active=2828  feature_norm=32.62
Iter 187 time=0.00  loss=345.57   active=2830  feature_norm=32.62
Iter 188 time=0.00  loss=345.56   active=2830  feature_norm=32.61
Iter 189 time=0.00  loss=345.53   active=2823  feature_norm=32.61
Iter 190 time=0.00  loss=345.53   active=2815  feature_norm=32.61
Iter 191 time=0.00  loss=345.51   active=2817  feature_norm=32.61
Iter 192 time=0.00  loss=345.51   active=2813  feature_norm=32.61
Iter 193 time=0.00  loss=345.49   active=2810  feature_norm=32.61
Iter 194 time=0.00  loss=345.48   active=2813  feature_norm=32.60
Iter 195 time=0.00  loss=345.46   active=2810  feature_norm=32.60
Iter 196 time=0.00  loss=345.44   active=2807  feature_norm=32.59
Iter 197 time=0.00  loss=345.43   active=2798  feature_norm=32.59
Iter 198 time=0.00  loss=345.41   active=2796  feature_norm=32.59
Iter 199 time=0.00  loss=345.40   active=2795  feature_norm=32.58
Iter 200 time=0.00  loss=345.39   active=2796  feature_norm=32.58
Iter 201 time=0.00  loss=345.38   active=2796  feature_norm=32.58
Iter 202 time=0.00  loss=345.37   active=2795  feature_norm=32.57
Iter 203 time=0.00  loss=345.36   active=2794  feature_norm=32.57
Iter 204 time=0.00  loss=345.36   active=2789  feature_norm=32.57
Iter 205 time=0.00  loss=345.35   active=2789  feature_norm=32.56
Iter 206 time=0.00  loss=345.35   active=2787  feature_norm=32.56
Iter 207 time=0.00  loss=345.34   active=2788  feature_norm=32.56
Iter 208 time=0.00  loss=345.34   active=2788  feature_norm=32.56
Iter 209 time=0.00  loss=345.33   active=2783  feature_norm=32.55
Iter 210 time=0.00  loss=345.33   active=2784  feature_norm=32.55
Iter 211 time=0.00  loss=345.33   active=2784  feature_norm=32.55
Iter 212 time=0.00  loss=345.32   active=2785  feature_norm=32.55
Iter 213 time=0.00  loss=345.32   active=2780  feature_norm=32.55
Iter 214 time=0.00  loss=345.32   active=2779  feature_norm=32.55
Iter 215 time=0.00  loss=345.31   active=2777  feature_norm=32.55
Iter 216 time=0.00  loss=345.31   active=2782  feature_norm=32.55
Iter 217 time=0.00  loss=345.31   active=2780  feature_norm=32.55
Iter 218 time=0.00  loss=345.30   active=2780  feature_norm=32.55
Iter 219 time=0.00  loss=345.30   active=2779  feature_norm=32.55
Iter 220 time=0.00  loss=345.30   active=2778  feature_norm=32.55
Iter 221 time=0.00  loss=345.30   active=2777  feature_norm=32.55
Iter 222 time=0.00  loss=345.29   active=2776  feature_norm=32.55
Iter 223 time=0.00  loss=345.29   active=2776  feature_norm=32.54
Iter 224 time=0.00  loss=345.29   active=2779  feature_norm=32.55
Iter 225 time=0.00  loss=345.29   active=2776  feature_norm=32.54
Iter 226 time=0.00  loss=345.28   active=2776  feature_norm=32.54
Iter 227 time=0.00  loss=345.28   active=2776  feature_norm=32.54
Iter 228 time=0.00  loss=345.28   active=2777  feature_norm=32.54
Iter 229 time=0.00  loss=345.28   active=2777  feature_norm=32.54
Iter 230 time=0.00  loss=345.28   active=2778  feature_norm=32.54
Iter 231 time=0.00  loss=345.27   active=2778  feature_norm=32.54
Iter 232 time=0.00  loss=345.27   active=2778  feature_norm=32.54
Iter 233 time=0.00  loss=345.27   active=2778  feature_norm=32.54
Iter 234 time=0.00  loss=345.27   active=2779  feature_norm=32.54
Iter 235 time=0.00  loss=345.27   active=2778  feature_norm=32.54
Iter 236 time=0.00  loss=345.26   active=2777  feature_norm=32.54
Iter 237 time=0.00  loss=345.26   active=2776  feature_norm=32.54
Iter 238 time=0.00  loss=345.26   active=2775  feature_norm=32.54
Iter 239 time=0.00  loss=345.26   active=2772  feature_norm=32.54
Iter 240 time=0.00  loss=345.26   active=2773  feature_norm=32.54
Iter 241 time=0.00  loss=345.26   active=2772  feature_norm=32.54
Iter 242 time=0.00  loss=345.25   active=2774  feature_norm=32.54
Iter 243 time=0.00  loss=345.25   active=2775  feature_norm=32.54
Iter 244 time=0.00  loss=345.25   active=2776  feature_norm=32.54
Iter 245 time=0.00  loss=345.25   active=2776  feature_norm=32.54
Iter 246 time=0.00  loss=345.25   active=2776  feature_norm=32.54
Iter 247 time=0.00  loss=345.25   active=2776  feature_norm=32.54
Iter 248 time=0.00  loss=345.25   active=2777  feature_norm=32.54
Iter 249 time=0.00  loss=345.24   active=2778  feature_norm=32.54
Iter 250 time=0.00  loss=345.24   active=2778  feature_norm=32.54
Iter 251 time=0.00  loss=345.24   active=2778  feature_norm=32.54
Iter 252 time=0.00  loss=345.24   active=2778  feature_norm=32.54
Iter 253 time=0.00  loss=345.24   active=2778  feature_norm=32.54
Iter 254 time=0.00  loss=345.24   active=2777  feature_norm=32.54
Iter 255 time=0.00  loss=345.24   active=2777  feature_norm=32.54
Iter 256 time=0.00  loss=345.24   active=2778  feature_norm=32.54
Iter 257 time=0.00  loss=345.23   active=2778  feature_norm=32.54
Iter 258 time=0.00  loss=345.23   active=2778  feature_norm=32.54
Iter 259 time=0.00  loss=345.23   active=2778  feature_norm=32.54
Iter 260 time=0.00  loss=345.23   active=2778  feature_norm=32.54
Iter 261 time=0.00  loss=345.23   active=2778  feature_norm=32.54
Iter 262 time=0.00  loss=345.23   active=2781  feature_norm=32.54
Iter 263 time=0.00  loss=345.23   active=2780  feature_norm=32.54
Iter 264 time=0.00  loss=345.23   active=2780  feature_norm=32.54
Iter 265 time=0.00  loss=345.23   active=2781  feature_norm=32.54
Iter 266 time=0.00  loss=345.22   active=2781  feature_norm=32.54
Iter 267 time=0.00  loss=345.22   active=2778  feature_norm=32.54
Iter 268 time=0.00  loss=345.22   active=2778  feature_norm=32.54
Iter 269 time=0.00  loss=345.22   active=2778  feature_norm=32.54
Iter 270 time=0.00  loss=345.22   active=2774  feature_norm=32.54
Iter 271 time=0.00  loss=345.22   active=2774  feature_norm=32.54
Iter 272 time=0.00  loss=345.22   active=2774  feature_norm=32.54
Iter 273 time=0.00  loss=345.22   active=2775  feature_norm=32.54
Iter 274 time=0.00  loss=345.21   active=2775  feature_norm=32.55
Iter 275 time=0.00  loss=345.21   active=2775  feature_norm=32.55
Iter 276 time=0.00  loss=345.21   active=2775  feature_norm=32.55
Iter 277 time=0.00  loss=345.21   active=2779  feature_norm=32.55
Iter 278 time=0.00  loss=345.21   active=2779  feature_norm=32.55
Iter 279 time=0.00  loss=345.21   active=2779  feature_norm=32.55
Iter 280 time=0.00  loss=345.21   active=2778  feature_norm=32.55
Iter 281 time=0.00  loss=345.21   active=2778  feature_norm=32.55
Iter 282 time=0.00  loss=345.21   active=2777  feature_norm=32.55
Iter 283 time=0.00  loss=345.21   active=2777  feature_norm=32.55
Iter 284 time=0.00  loss=345.20   active=2777  feature_norm=32.55
Iter 285 time=0.00  loss=345.20   active=2781  feature_norm=32.55
Iter 286 time=0.00  loss=345.20   active=2782  feature_norm=32.55
Iter 287 time=0.00  loss=345.20   active=2782  feature_norm=32.55
Iter 288 time=0.00  loss=345.20   active=2780  feature_norm=32.55
Iter 289 time=0.00  loss=345.20   active=2780  feature_norm=32.55
Iter 290 time=0.00  loss=345.20   active=2780  feature_norm=32.55
Iter 291 time=0.00  loss=345.20   active=2780  feature_norm=32.55
Iter 292 time=0.00  loss=345.20   active=2778  feature_norm=32.55
Iter 293 time=0.00  loss=345.20   active=2778  feature_norm=32.55
Iter 294 time=0.00  loss=345.20   active=2778  feature_norm=32.55
Iter 295 time=0.00  loss=345.20   active=2777  feature_norm=32.55
Iter 296 time=0.00  loss=345.19   active=2773  feature_norm=32.55
Iter 297 time=0.00  loss=345.19   active=2773  feature_norm=32.55

### Results on the validation set

In [125]:
def flatten(l):
    result = []
    for sub in l:
        result.extend(sub)
    return result

y_pred = crf.predict(dev_dicts)
print(f1_score(flatten(dev_tags), flatten(y_pred), average='macro'))
print(f1_score(flatten(dev_tags), flatten(y_pred), average='micro'))
print(classification_report(flatten(dev_tags), flatten(y_pred)))

0.6785211515324803
0.9174468085106382
              precision    recall  f1-score   support

 I-ATTRIBUTE       0.84      0.78      0.81       246
    I-COLOUR       0.92      0.62      0.74        56
  I-MATERIAL       1.00      0.57      0.72        37
     I-PRICE       1.00      0.20      0.33        15
   I-PRODUCT       0.92      0.87      0.89       341
     I-SHAPE       1.00      0.36      0.53        11
      I-SIZE       0.96      0.96      0.96       184
   I-TEXTURE       1.00      0.08      0.15        12
           O       0.92      0.98      0.95      1448

    accuracy                           0.92      2350
   macro avg       0.95      0.60      0.68      2350
weighted avg       0.92      0.92      0.91      2350

### Tagging the Validation set

In [126]:
val_set= pd.read_csv('un-negated_clean_data.csv')

In [127]:
val_set

       Tokens       Tags  is_negative  sentence
0           I          O        False         0
1          am          O        False         0
2     looking          O        False         0
3         for          O        False         0
4           a          O        False         0
...       ...        ...          ...       ...
2345       30     B-SIZE        False       166
2346     inch     I-SIZE        False       166
2347    white   B-COLOUR        False       166
2348     desk  B-PRODUCT        False       166
2349      set  I-PRODUCT        False       166

[2350 rows x 4 columns]

In [128]:
token_list = val_set.Tokens.values.tolist()
sentence_list = val_set.sentence.values.tolist()

In [130]:
import csv
rows = zip(sentence_list,token_list,flatten(y_pred))
with open('Heyday_validationdata.csv', "w") as f:
    writer = csv.writer(f)
    writer.writerow(('Sentence_Index','Tokens','Predicted_NER_Tags'))
    for row in rows:
        writer.writerow(row)